server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: payment-1
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      acks: all

management.endpoints.web.exposure.include: health,info,prometheus
