global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-apps'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
          - host.docker.internal:8081
          - host.docker.internal:8084
          - host.docker.internal:8085
          - host.docker.internal:8091
          - host.docker.internal:8089
          - host.docker.internal:8095
