apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-svc
  labels:
    app: inventory-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-svc
  template:
    metadata:
      labels:
        app: inventory-svc
    spec:
      containers:
      - name: inventory-svc
        image: inventory-svc:latest
