name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Maven Verify
        run: mvn -B -ntp -DskipTests=false verify

      - name: Aggregate JARs (optional)
        if: ${{ success() }}
        run: |
          mkdir -p artifacts
          find . -name "*.jar" -path "*/target/*" -maxdepth 3 -print -exec cp {} artifacts/ \;

      - name: Upload Artifacts (optional)
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: artifacts
